version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    environment:
      - APP_ID: hlhabhmnklidddklapmklccngaofgfim
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install curl jq
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Tests
          command: npm run test
      - run:
          name: Add Build Number to Manifest
          command: node append_build_number.js ${CIRCLE_BUILD_NUM}
      - run:
          name: Build and Zip
          command: npm run ci-prod
      - store_artifacts:
          path: build
          destination: build/
      - run:
          name: Publish to Web Store
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T mercurywm-*.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
            fi
